### ISSUE TITLE
Add sound Effects

### ISSUE THREAD

**Issue by manishkrjha** [RishabhDevbanshi/Pacman-Game#104]
A sound effect can be added after major events (for e.g. victory sound, Game over sound etc).

**Comment by RishabhDevbanshi** [comment]
> A sound effect can be added after major events (for e.g. victory sound, Game over sound etc).

I think someone already had made the pull request regarding the same. You can check in Pull Request section if it is there then close the issue else you can work on it.

**Comment by manishkrjha** [comment]
Didn't noticed that, apologies.
