### ISSUE TITLE
Updated the CSS file

### ISSUE THREAD

**Issue by habyaad** [RishabhDevbanshi/Pacman-Game#19]
The game has a poor UI

**Comment by RishabhDevbanshi** [comment]
You can work on it and make it better !

**Comment by habyaad** [comment]
Fine

**Comment by Mitali-laroia** [comment]
Can I also work on this issue?

**Comment by Gztabo21** [comment]
wow,

**Comment by Gztabo21** [comment]
great code ,
I will update the code

**Comment by Gztabo21** [comment]
can i change the color?

**Comment by tanujajoshi1** [comment]
Can I change color and do little modifications with its UI?

**Comment by Ayush-Khandelwal-007** [comment]
Please give me a chance. I would like to contribute.

**Comment by Gztabo21** [comment]
#45

**Comment by Gztabo21** [comment]
update css  verifi

**Comment by RishabhDevbanshi** [comment]
Everybody can do it, it is open for all and for those who already did that please wait a liitle while. As you can see there are  so many PRs so it will take some time for me to look at your PR , but I will look at it definitely. SO please have a little patience, thank you !
