### ISSUE TITLE
Where is Readme.md ?

### ISSUE THREAD

**Issue by RishabhDevbanshi** [RishabhDevbanshi/Pacman-Game#3]
It would be helpful if someone can help to create Readme for this project.

**Comment by shubham2704** [comment]
Hello @RishabhDevbanshi , I would like to contribute to this issue.

**Comment by bhavesh1129** [comment]
Can you please tell lil bit about the project?

**Comment by royadeveloper01** [comment]
Can you drop a rundown of the project??

**Comment by RishabhDevbanshi** [comment]
It is open for all, anyone can contribute.

**Comment by tanujajoshi1** [comment]
I've given a try to improve readme

**Comment by Ayush-Khandelwal-007** [comment]
I would like to help. Please assign me.

**Comment by RishabhDevbanshi** [comment]
@tanujajoshi1 , will surely look at it.
@Ayush-Khandelwal-007 go on.
