### ISSUE TITLE
Home page 

### ISSUE THREAD

**Issue by TechLead-War** [RishabhDevbanshi/Pacman-Game#35]
The game starts without any interaction of the user, like start button, or so.

**Comment by TaarnStar** [comment]
Hi @AyushTechlead, can I help with this issue?

**Comment by TechLead-War** [comment]
sure.

**Comment by TaarnStar** [comment]
@AyushTechlead cool, I see that someone already pushed a commit regarding the homepage, so probably my help isn't needed anymore :)
