### ISSUE TITLE
No movement on tap and hold, Player only move on taping

### ISSUE THREAD

**Issue by ut-01** [RishabhDevbanshi/Pacman-Game#57]
I tried playing the game through keyboard and I have to tap like a million times to get points. It would be definitely more comfortable if it work on tap and holding the arrow keys.

**Comment by RishabhDevbanshi** [comment]
I too think same, but as you can see that the ghosts aren't moving behind pacman , thus right now making change fro keyup to keydown will make it super simple, which what no one wants. Once that issue is resolved I will change the keyup to keydown.
