### ISSUE TITLE
Add Buttons to screen

### ISSUE THREAD

**Issue by RishabhDevbanshi** [RishabhDevbanshi/Pacman-Game#9]
As you know , right now we can control pacman by just keyboard arrow buttons, it would be great if we also add 4 on-screen buttons, and we can control pacman movements by pressing those buttons.

**Comment by gyadav-prog** [comment]
Okay Rishabh I will add buttons on the screen and give them a functionality

**Comment by RishabhDevbanshi** [comment]
> Okay Rishabh I will add buttons on the screen and give them a functionality

GO Ahead!

**Comment by ssmkhrj** [comment]
I have made a pull request regarding the same. Also, I have tried to make the least possible changes to the existing code.

**Comment by hariomkushwaha** [comment]
I also want to contribute to this

**Comment by Sukriti-sood** [comment]
Hey @RishabhDevbanshi , Can you assigned me this?

**Comment by RishabhDevbanshi** [comment]
> I also want to contribute to this

Go ON1

**Comment by RishabhDevbanshi** [comment]
> Hey @RishabhDevbanshi , Can you assigned me this?

@Sukriti-sood Go Ahead with it.

**Comment by muhammadev** [comment]
I want to contribute. Can you assign me, please?

**Comment by RishabhDevbanshi** [comment]
@muhammadev  It's open for everyone. You can surely give it a shot !

**Comment by Parth-Gupta10** [comment]
@RishabhDevbanshi I have send a PR please check

**Comment by tanujajoshi1** [comment]
I would like to contribute here

**Comment by TrendingLedger** [comment]
Hey how do I contribute? What can I do to help?

**Comment by jozzbruer** [comment]
Check my pull request @RishabhDevbanshi

**Comment by RishabhDevbanshi** [comment]
Everyone go on with it.
I will check all pull requests, it may take some time but I will check them for sure !

**Comment by pranalishinde28** [comment]
i think UI should be fixed. Please let me know if I can help :)

**Comment by jozzbruer** [comment]
I’ll focus on UI later

**Comment by askjag07** [comment]
#62 Done. 3D buttons are now available to play the game in a retro style.

**Comment by AyushRajSharma** [comment]
[Added some cool looking 3D button](https://github.com/RishabhDevbanshi/Pacman-Game/pull/63).

**Comment by DenseOriginal** [comment]
Can I help, adding buttons without changing the underlying code?

**Comment by askjag07** [comment]
#69 Fixed the new UI.

Added 3D buttons with cool new UI. Hope this is good for you:
<img width="736" alt="Screen Shot 2020-10-02 at 9 24 07 PM" src="https://user-images.githubusercontent.com/67054376/94943859-fba00900-04f5-11eb-8115-9c2dd8208297.png">

**Comment by TheEternalChamption** [comment]
What can I help with?

**Comment by adaugochi** [comment]
I just created a PR.

**Comment by anveshreddy18** [comment]
Hii, I would like to contribute to this.

**Comment by saber1-star** [comment]
i am still learning but i would like to make a contribution as well

**Comment by Vineeth737** [comment]
I want to contribute

**Comment by bunny8469** [comment]
Added the arrow buttons.
![pacmann](https://user-images.githubusercontent.com/58695175/94983928-9800f480-0564-11eb-9842-6760a4b1f4e0.png)
I made a [PR](https://github.com/RishabhDevbanshi/Pacman-Game/pull/80#issue-497216220)
I'm waiting for my pull request to be reviewed.

**Comment by ghost** [comment]
lol.
