### ISSUE TITLE
Turn this game available in GitHub Pages

### ISSUE THREAD

**Issue by luiseduardogfranca** [RishabhDevbanshi/Pacman-Game#99]
This project is executed by **index.html**, than just active GitHub pages in the settings and put the URL in README.md.

- [ ] Enable the GitHub Pages in the settings 
- [ ] Put the URL in README.md

**Comment by Hack-Light** [comment]
Is this up for grabs

**Comment by RishabhDevbanshi** [comment]
It's already active on Github Pages. Check the link of the game once again.
